export enum UserRole {
  PLATFORM_ADMIN = 'PLATFORM_ADMIN',
  REGIONAL_ADMIN = 'REGIONAL_ADMIN',
  SUPPORT_MODERATOR = 'SUPPORT_MODERATOR',
  FARMER = 'FARMER',
  BUYER = 'BUYER',
  TESTER = 'TESTER',
  EXPERT = 'EXPERT',
}